server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: ${APP_NAME:Auth JWT API}

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:auth_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 6MB

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

  security:
    jwt:
      issuer: ${JWT_ISSUER:auth-jwt}
      access:
        secret: ${JWT_ACCESS_SECRET:dev-access-secret-change-me}
        expiration-minutes: ${JWT_ACCESS_EXP_MIN:15}
      refresh:
        secret: ${JWT_REFRESH_SECRET:dev-refresh-secret-change-me}
        expiration-days: ${JWT_REFRESH_EXP_DAYS:14}

  uploads:
    profile-dir: ${UPLOAD_PROFILE_DIR:uploads/profile-pictures}
    profile-url-prefix: ${UPLOAD_PROFILE_URL_PREFIX:/uploads/profile-pictures}

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs
